language: php

php:
 - 5.3
 - 5.4

before_install:
 - composer install --dev

before_script:
 - cp phpunit.xml.dist phpunit.xml

script:
 - vendor/bin/phpunit

notifications:
  email: "widmogrod+zf2-assetic-module@gmail.com"
